version: '3.8'

services:
  eureka-server:
    image: eureka-server:latest  # Replace with your Eureka Server Docker image
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - gateway-net

  apigateway:
    build: .  # This tells Docker to build the Dockerfile in the current directory
    container_name: apigateway
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_SERVER=http://eureka-server:8761/eureka
    networks:
      - gateway-net

  order-service:
    image: order-service:latest  # Replace with your Order Service Docker image
    container_name: order-service
    networks:
      - gateway-net

  product-service:
    image: product-service:latest  # Replace with your Product Service Docker image
    container_name: product-service
    networks:
      - gateway-net

  user-service:
    image: user-service:latest  # Replace with your User Service Docker image
    container_name: user-service
    networks:
      - gateway-net

networks:
  gateway-net:
    driver: bridge
